spring:
  application:
    name: budget-buddy-api
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}
          audiences: ${OIDC_AUDIENCES}

server:
  port: ${SERVER_PORT:8080}

logging:
  pattern:
    correlation: "[%X{requestId:-}] [%X{userId:-}] "

security:
  cors:
    allowed-origin-patterns: [ ]
    allowed-methods: [ GET, POST, PUT, DELETE, OPTIONS ]
    allowed-headers: [ "*" ]
    allow-credentials: true
    max-age: 3600
