spring:
  docker:
    compose:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://test-issuer.example.com

security:
  cors:
    allowed-origin-patterns:
      - "http://localhost:[*]"
  refresh-token:
    validity-seconds: 1209600 # 14 days
    cleanup:
      enabled: false
